language: ruby

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0

env:
  - "RAILS_VERSION=3.1.0"
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.2.0"

matrix:
  include:
    # Rails 5.x only supports 2.2+
    - rvm: 2.3.0
      env: RAILS_VERSION=master
    - rvm: 2.3.0
      env: RAILS_VERSION=5.0.0
    - rvm: 2.2.2
      env: RAILS_VERSION=5.0.0

allow_failures:
  - rvm: 2.3.0
    env: RAILS_VERSION=master

notifications:
  email: false
